
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("8ac481fc-dc72-4345-a574-831f610fa831")>
Namespace CustomerManagementModel
    
    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class Entities
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=Entities", "Entities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new Entities object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "Entities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new Entities object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "Entities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Countries() As ObjectSet(Of Country)
            Get
                If (_Countries Is Nothing) Then
                    _Countries = MyBase.CreateObjectSet(Of Country)("Countries")
                End If
                Return _Countries
            End Get
        End Property
    
        Private _Countries As ObjectSet(Of Country)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Customers() As ObjectSet(Of Customer)
            Get
                If (_Customers Is Nothing) Then
                    _Customers = MyBase.CreateObjectSet(Of Customer)("Customers")
                End If
                Return _Customers
            End Get
        End Property
    
        Private _Customers As ObjectSet(Of Customer)

        #End Region
        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Countries EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToCountries(ByVal country As Country)
            MyBase.AddObject("Countries", country)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToCustomers(ByVal customer As Customer)
            MyBase.AddObject("Customers", customer)
        End Sub

        #End Region
    End Class

    #End Region
    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="CustomerManagementModel", Name:="Country")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Country
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Country object.
        ''' </summary>
        ''' <param name="id">Initial value of the ID property.</param>
        ''' <param name="name">Initial value of the Name property.</param>
        ''' <param name="dialingCountryCode">Initial value of the DialingCountryCode property.</param>
        ''' <param name="internationalDialingCode">Initial value of the InternationalDialingCode property.</param>
        ''' <param name="internetTLD">Initial value of the InternetTLD property.</param>
        Public Shared Function CreateCountry(id As Global.System.Guid, name As Global.System.String, dialingCountryCode As Global.System.String, internationalDialingCode As Global.System.String, internetTLD As Global.System.String) As Country
            Dim country as Country = New Country
            country.ID = id
            country.Name = name
            country.DialingCountryCode = dialingCountryCode
            country.InternationalDialingCode = internationalDialingCode
            country.InternetTLD = internetTLD
            Return country
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ID() As Global.System.Guid
            Get
                Return _ID
            End Get
            Set
                If (_ID <> Value) Then
                    OnIDChanging(value)
                    ReportPropertyChanging("ID")
                    _ID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("ID")
                    OnIDChanged()
                End If
            End Set
        End Property
    
        Private _ID As Global.System.Guid
        Private Partial Sub OnIDChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Name() As Global.System.String
            Get
                Return _Name
            End Get
            Set
                OnNameChanging(value)
                ReportPropertyChanging("Name")
                _Name = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Name")
                OnNameChanged()
            End Set
        End Property
    
        Private _Name As Global.System.String
        Private Partial Sub OnNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property PhoneNoFormat() As Global.System.String
            Get
                Return _PhoneNoFormat
            End Get
            Set
                OnPhoneNoFormatChanging(value)
                ReportPropertyChanging("PhoneNoFormat")
                _PhoneNoFormat = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("PhoneNoFormat")
                OnPhoneNoFormatChanged()
            End Set
        End Property
    
        Private _PhoneNoFormat As Global.System.String
        Private Partial Sub OnPhoneNoFormatChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPhoneNoFormatChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property DialingCountryCode() As Global.System.String
            Get
                Return _DialingCountryCode
            End Get
            Set
                OnDialingCountryCodeChanging(value)
                ReportPropertyChanging("DialingCountryCode")
                _DialingCountryCode = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("DialingCountryCode")
                OnDialingCountryCodeChanged()
            End Set
        End Property
    
        Private _DialingCountryCode As Global.System.String
        Private Partial Sub OnDialingCountryCodeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnDialingCountryCodeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property InternationalDialingCode() As Global.System.String
            Get
                Return _InternationalDialingCode
            End Get
            Set
                OnInternationalDialingCodeChanging(value)
                ReportPropertyChanging("InternationalDialingCode")
                _InternationalDialingCode = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("InternationalDialingCode")
                OnInternationalDialingCodeChanged()
            End Set
        End Property
    
        Private _InternationalDialingCode As Global.System.String
        Private Partial Sub OnInternationalDialingCodeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnInternationalDialingCodeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property InternetTLD() As Global.System.String
            Get
                Return _InternetTLD
            End Get
            Set
                OnInternetTLDChanging(value)
                ReportPropertyChanging("InternetTLD")
                _InternetTLD = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("InternetTLD")
                OnInternetTLDChanged()
            End Set
        End Property
    
        Private _InternetTLD As Global.System.String
        Private Partial Sub OnInternetTLDChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnInternetTLDChanged()
        End Sub

        #End Region
    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="CustomerManagementModel", Name:="Customer")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Customer
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Customer object.
        ''' </summary>
        ''' <param name="id">Initial value of the ID property.</param>
        ''' <param name="firstName">Initial value of the FirstName property.</param>
        ''' <param name="lastName">Initial value of the LastName property.</param>
        ''' <param name="address">Initial value of the Address property.</param>
        ''' <param name="zipCode">Initial value of the ZipCode property.</param>
        ''' <param name="city">Initial value of the City property.</param>
        ''' <param name="countryID">Initial value of the CountryID property.</param>
        ''' <param name="url">Initial value of the Url property.</param>
        ''' <param name="creditLimit">Initial value of the CreditLimit property.</param>
        ''' <param name="newsSubscriber">Initial value of the NewsSubscriber property.</param>
        ''' <param name="createdDate">Initial value of the CreatedDate property.</param>
        ''' <param name="createdBy">Initial value of the CreatedBy property.</param>
        Public Shared Function CreateCustomer(id As Global.System.Guid, firstName As Global.System.String, lastName As Global.System.String, address As Global.System.String, zipCode As Global.System.String, city As Global.System.String, countryID As Global.System.Guid, url As Global.System.String, creditLimit As Global.System.Int32, newsSubscriber As Global.System.Boolean, createdDate As Global.System.DateTime, createdBy As Global.System.String) As Customer
            Dim customer as Customer = New Customer
            customer.ID = id
            customer.FirstName = firstName
            customer.LastName = lastName
            customer.Address = address
            customer.ZipCode = zipCode
            customer.City = city
            customer.CountryID = countryID
            customer.Url = url
            customer.CreditLimit = creditLimit
            customer.NewsSubscriber = newsSubscriber
            customer.CreatedDate = createdDate
            customer.CreatedBy = createdBy
            Return customer
        End Function

        #End Region
        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ID() As Global.System.Guid
            Get
                Return _ID
            End Get
            Set
                If (_ID <> Value) Then
                    OnIDChanging(value)
                    ReportPropertyChanging("ID")
                    _ID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("ID")
                    OnIDChanged()
                End If
            End Set
        End Property
    
        Private _ID As Global.System.Guid
        Private Partial Sub OnIDChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property FirstName() As Global.System.String
            Get
                Return _FirstName
            End Get
            Set
                OnFirstNameChanging(value)
                ReportPropertyChanging("FirstName")
                _FirstName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("FirstName")
                OnFirstNameChanged()
            End Set
        End Property
    
        Private _FirstName As Global.System.String
        Private Partial Sub OnFirstNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnFirstNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property LastName() As Global.System.String
            Get
                Return _LastName
            End Get
            Set
                OnLastNameChanging(value)
                ReportPropertyChanging("LastName")
                _LastName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("LastName")
                OnLastNameChanged()
            End Set
        End Property
    
        Private _LastName As Global.System.String
        Private Partial Sub OnLastNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnLastNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Address() As Global.System.String
            Get
                Return _Address
            End Get
            Set
                OnAddressChanging(value)
                ReportPropertyChanging("Address")
                _Address = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Address")
                OnAddressChanged()
            End Set
        End Property
    
        Private _Address As Global.System.String
        Private Partial Sub OnAddressChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnAddressChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Phone() As Global.System.String
            Get
                Return _Phone
            End Get
            Set
                OnPhoneChanging(value)
                ReportPropertyChanging("Phone")
                _Phone = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Phone")
                OnPhoneChanged()
            End Set
        End Property
    
        Private _Phone As Global.System.String
        Private Partial Sub OnPhoneChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnPhoneChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ZipCode() As Global.System.String
            Get
                Return _ZipCode
            End Get
            Set
                OnZipCodeChanging(value)
                ReportPropertyChanging("ZipCode")
                _ZipCode = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("ZipCode")
                OnZipCodeChanged()
            End Set
        End Property
    
        Private _ZipCode As Global.System.String
        Private Partial Sub OnZipCodeChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnZipCodeChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property City() As Global.System.String
            Get
                Return _City
            End Get
            Set
                OnCityChanging(value)
                ReportPropertyChanging("City")
                _City = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("City")
                OnCityChanged()
            End Set
        End Property
    
        Private _City As Global.System.String
        Private Partial Sub OnCityChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCityChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property State() As Global.System.String
            Get
                Return _State
            End Get
            Set
                OnStateChanging(value)
                ReportPropertyChanging("State")
                _State = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("State")
                OnStateChanged()
            End Set
        End Property
    
        Private _State As Global.System.String
        Private Partial Sub OnStateChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnStateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CountryID() As Global.System.Guid
            Get
                Return _CountryID
            End Get
            Set
                OnCountryIDChanging(value)
                ReportPropertyChanging("CountryID")
                _CountryID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("CountryID")
                OnCountryIDChanged()
            End Set
        End Property
    
        Private _CountryID As Global.System.Guid
        Private Partial Sub OnCountryIDChanging(value As Global.System.Guid)
        End Sub
    
        Private Partial Sub OnCountryIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property EmailAddress() As Global.System.String
            Get
                Return _EmailAddress
            End Get
            Set
                OnEmailAddressChanging(value)
                ReportPropertyChanging("EmailAddress")
                _EmailAddress = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("EmailAddress")
                OnEmailAddressChanged()
            End Set
        End Property
    
        Private _EmailAddress As Global.System.String
        Private Partial Sub OnEmailAddressChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnEmailAddressChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Url() As Global.System.String
            Get
                Return _Url
            End Get
            Set
                OnUrlChanging(value)
                ReportPropertyChanging("Url")
                _Url = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Url")
                OnUrlChanged()
            End Set
        End Property
    
        Private _Url As Global.System.String
        Private Partial Sub OnUrlChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnUrlChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CreditLimit() As Global.System.Int32
            Get
                Return _CreditLimit
            End Get
            Set
                OnCreditLimitChanging(value)
                ReportPropertyChanging("CreditLimit")
                _CreditLimit = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("CreditLimit")
                OnCreditLimitChanged()
            End Set
        End Property
    
        Private _CreditLimit As Global.System.Int32
        Private Partial Sub OnCreditLimitChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnCreditLimitChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property NewsSubscriber() As Global.System.Boolean
            Get
                Return _NewsSubscriber
            End Get
            Set
                OnNewsSubscriberChanging(value)
                ReportPropertyChanging("NewsSubscriber")
                _NewsSubscriber = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("NewsSubscriber")
                OnNewsSubscriberChanged()
            End Set
        End Property
    
        Private _NewsSubscriber As Global.System.Boolean
        Private Partial Sub OnNewsSubscriberChanging(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnNewsSubscriberChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CreatedDate() As Global.System.DateTime
            Get
                Return _CreatedDate
            End Get
            Set
                OnCreatedDateChanging(value)
                ReportPropertyChanging("CreatedDate")
                _CreatedDate = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("CreatedDate")
                OnCreatedDateChanged()
            End Set
        End Property
    
        Private _CreatedDate As Global.System.DateTime
        Private Partial Sub OnCreatedDateChanging(value As Global.System.DateTime)
        End Sub
    
        Private Partial Sub OnCreatedDateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CreatedBy() As Global.System.String
            Get
                Return _CreatedBy
            End Get
            Set
                OnCreatedByChanging(value)
                ReportPropertyChanging("CreatedBy")
                _CreatedBy = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("CreatedBy")
                OnCreatedByChanged()
            End Set
        End Property
    
        Private _CreatedBy As Global.System.String
        Private Partial Sub OnCreatedByChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCreatedByChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ModifiedDate() As Nullable(Of Global.System.DateTime)
            Get
                Return _ModifiedDate
            End Get
            Set
                OnModifiedDateChanging(value)
                ReportPropertyChanging("ModifiedDate")
                _ModifiedDate = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ModifiedDate")
                OnModifiedDateChanged()
            End Set
        End Property
    
        Private _ModifiedDate As Nullable(Of Global.System.DateTime)
        Private Partial Sub OnModifiedDateChanging(value As Nullable(Of Global.System.DateTime))
        End Sub
    
        Private Partial Sub OnModifiedDateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ModifiedBy() As Global.System.String
            Get
                Return _ModifiedBy
            End Get
            Set
                OnModifiedByChanging(value)
                ReportPropertyChanging("ModifiedBy")
                _ModifiedBy = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("ModifiedBy")
                OnModifiedByChanged()
            End Set
        End Property
    
        Private _ModifiedBy As Global.System.String
        Private Partial Sub OnModifiedByChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnModifiedByChanged()
        End Sub

        #End Region
    End Class

    #End Region
    
End Namespace
